### ISSUE TITLE
Elaborar Rich Picture 

### ISSUE THREAD

**Issue by inddiara** [DesenhoSoftware-2018-2/wiki#1]
Nessa issue deverá ser feito:

Elaborar versão inicial do artefato Rich Picture da aplicação desenvolvida na disciplina.

Critérios de aceitação:
- Todos os richpictures documentados na wiki

**Comment by inddiara** [comment]
Nessa issue deverá ser feito:

- Elaborar versão inicial do artefato Rich Picture da aplicação a ser desenvolvida na disciplina.

**Comment by alvesisaque** [comment]
Galera, eu já criei a branch para a gente colocar os richpictures. é essa aqui: https://github.com/DesenhoSoftware-2018-2/wiki/tree/1_richpictures

**Comment by alvesisaque** [comment]
Pessoal, iniciei a página e coloquei meus rich pictures lá, mas ficou bagunçado pq eu não consegui definir um tabanho para as imagens. Alguém pode me ajudar? tentei seguir essas dicas mas não da certo: https://stackoverflow.com/questions/49074666/changing-image-size-in-markdown-on-gitlab, https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown.
