### ISSUE TITLE
Inserir as ferramentas utilizadas 

### ISSUE THREAD

**Issue by lucianaribeiro** [DesenhoSoftware-2018-2/wiki#12]
Nessa issue deve ser feito:

  - Inserir na wiki as ferramentas abaixo que estão sendo utilizadas
  - [x] Drive
  - [x] Telegram
  - [x] Github
  - [x] Zenhub
  - [x] Hangouts

Critérios de aceitação:
 - Ter logo para cada ferramenta
 - Estar tudo na wiki 
 - Ser responsivo

**Comment by inddiara** [comment]
Adição de ferramentas:
- Visual Studio Code
- Bizagi
- Marvel
