### ISSUE TITLE
Criar Formulário

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [DesenhoSoftware-2018-2/wiki#2]
Nessa issue deverá ser feito:

- [x] Criar formulário para recolher dados do público alvo, usando google form.
- [x] Disponibilizar o formulário no grupo do Facebook da Fga.
- [x] Documentar o formulário e a análise do mesmo na wiki.

**Comment by CalebeRios** [comment]
Já rodamos esse formulário né? Já esta na wiki?

**Comment by BrunoOliveiraDantas** [comment]
Sim, já está na wiki. @CalebeRios  pode validar, por favor.
