### ISSUE TITLE
Criar First Thing First

### ISSUE THREAD

**Issue by BrunoOliveiraDantas** [DesenhoSoftware-2018-2/wiki#39]
Nessa issue deverá ser feito:

- First Thing First para priorização do projeto .

Critérios de aceitação:

- Estar documentado na wiki.

**Comment by alvesisaque** [comment]
Gente, eu não conheço nada disso aqui. Vocês podem me indicar links para me atualizar?

**Comment by CalebeRios** [comment]
@alvesisaque Nós temos uma planilha que utilizamos em requisitos. Iremos criar uma para desenho e irei procurar materiais que utilizamos em requisitos e colocar aqui também

**Comment by CalebeRios** [comment]
A Planilha já esta criada no nosso drive, esta em dinamica 2 -> priorização de requisitos.

**Comment by AmandaMuniz** [comment]
https://docs.google.com/spreadsheets/d/1sBDEHw4TPSpMc1ZcfQxRJINb7Qu1h9YR8lz0Dr-kvTY/edit?usp=sharing

**Comment by AmandaMuniz** [comment]
Para ajudar quem não lembra a responder o TFT:

- **Beneficio Relativo** = o quanto o requisito beneficia o usuário caso atendido (em uma escala de 1 a 9).
- **Penalidade Relativa** = o quanto o requisito prejudica o usuário caso não atendido (em uma escala de 1 a 9).
- **Valor Total** = a soma do Beneficio Relativo e da Penalidade Relativa.
- **Valor %** = a porcentagem que o valor total de um requisito representa da soma de todos os valores totais.
- **Custo Relativo** = o custo de garantir que o requisito será atendido (em uma escala de 1 a 9).
- **Custo %** = a porcentagem que o Custo Relativo de um requisito representa da soma de todos os Custos Relativos.
- **Risco Relativo** = o risco de implementação de um requisito (em uma escala de 1 a 9).
- **Risco %** = a porcentagem que o Risco Relativo de um requisito representa da soma de todos os Riscos Relativos.
- **Prioridade** = Valor %/ (Custo % + Risco %).

**Comment by alvesisaque** [comment]
@AmandaMuniz onde eu acho a lista dos requisitos pra usar como base na pontuação.

**Comment by AmandaMuniz** [comment]
https://docs.google.com/document/d/1amPh6Ydl0LUsy0TRXN-vRnZLcS2zR1TTHuokyHQKWDc/edit?usp=sharing

**Comment by alvesisaque** [comment]
@AmandaMuniz obrigado

**Comment by CalebeRios** [comment]
Todos já responderam o FTF, irei pegar os dados e subir na Wiki
