### ISSUE TITLE
Criar logo do projeto

### ISSUE THREAD

**Issue by lucianaribeiro** [DesenhoSoftware-2018-2/wiki#4]
Nessa issue deve ser feito:
  - [x] Criar logo que represente o projeto

Critérios de aceitação:

  - Estar na wiki
  - Estar no README do projeto

**Comment by BrunoOliveiraDantas** [comment]
![banquinha](https://user-images.githubusercontent.com/22121504/44662466-3d3f5b00-a9e4-11e8-945d-5214f40afba9.png)

**Comment by BrunoOliveiraDantas** [comment]
Versão inicial da logo do projeto terminada.
