### ISSUE TITLE
Fazer o Documento de Visão

### ISSUE THREAD

**Issue by CalebeRios** [DesenhoSoftware-2018-2/wiki#40]
Nessa issue deverá ser feito:

- Documento de Visão

Critérios de aceitação:

- Estar documentado na wiki.

**Comment by alvesisaque** [comment]
Ahh, amei vamos usar o modelo do RUP né?

**Comment by CalebeRios** [comment]
@alvesisaque Isso isso! Se puder já ir criando o template para a gente usar
