### ISSUE TITLE
Fazer guia de instalação 

### ISSUE THREAD

**Issue by AmandaMuniz** [DesenhoSoftware-2018-2/wiki#57]
Nesta issue deverá ser feito:
- Guia de instalação do React Native

Critérios de aceitação:

- [ ] Estar documentado nos docs da wiki.

**Comment by CalebeRios** [comment]
@AmandaMuniz Esse guia é para as pessoas saberem como instalar o react native e criar um novo projeto, ou para eles saberem como rodar o nosso projeto??

**Comment by AmandaMuniz** [comment]
@CalebeRios É um guia de instalação do ambiente
