### ISSUE TITLE
Definir metodologias

### ISSUE THREAD

**Issue by inddiara** [DesenhoSoftware-2018-2/wiki#6]
Nessa issue deverá ser feito:

- Definir tipo de metodologia a ser utilizada;

Citérios de aceitação:
- Devidamente documentado na wiki

**Comment by alvesisaque** [comment]
https://github.com/projeto-cascata

**Comment by alvesisaque** [comment]
https://github.com/Desenho-2-2017/Ecom_merci/wiki
