### ISSUE TITLE
Documento de arquitetura

### ISSUE THREAD

**Issue by alvesisaque** [DesenhoSoftware-2018-2/wiki#63]
Nessa issue deverá ser feito:

Critérios de aceitação:
- revisada e documentada na wiki

**Comment by alvesisaque** [comment]
gente, eu to achando essa issue muito grande. Dentro de um doc de arquitetura tem muitas outras coisas como diagrama de classes, modelagem do banco, relações entre outros. talvez essa issue deva ser um épico e essas atividades quebradas dentro e cada uma com responsáveis. 

O que acham?

**Comment by alvesisaque** [comment]
## Resultado do estudo

Após algumas horas de estudos , falar com a Carla e com alguns gestores do meu 
trabalho cheguei ao consenso que devemos continuar mensurando as métricas e cultura 
subjetivas como velocity e pontuação das issues, mas também devemos mensurar os dados 
concretos da realização das atividades, como o **gráfico de controle, thoughtput (vazão) e acumulative flow**. 

### Métricas com pontuação

As métricas que utilizam a pontuação tendem a ser mais subjetivas ao entendimento 
da equipe.
Essa métrica é muito bem utilizada para equipes menores e que o processo é rápido.

Ela é coletada atualmente no git mesmo, entra lá pra dar uma olhada: https://github.com/eliseuegewarth/ws-software#reports?report=velocity

## Métricas com estatística

São as métricas que utilizam o histórico das issues para mensurar e levantar indicadores.

Muito bem utilizadas quando a eficiência do processo é baixa e não interfere no esforco da issue.

Também pode ser aproveitada dentro do nosso contexto como auxiliar no histórico 
real do time, ajudar a verificar se o que o time pontua reflete na duração do trabalho.

### O gráfico de controle
Indica a taxa de confiança de entrega assim como o velocity, mas essa é voltada para as informações menos subjetivas. 
Para saber a média de quantos dias leva para entregar uma certa quantidade de issues de acordo com o tempo que cada uma delas leva para ser fechada.

<img width="338" alt="capture1" src="https://user-images.githubusercontent.com/17963713/47404670-94cc1f80-d724-11e8-9d4c-0f6538f63d1e.PNG">

### Gráfico de vasão

Apresenta e indica em quantos dias uma certa quantidade de pontos é entregue em relação à quantidade de issues fechadas. 

<img width="337" alt="capture3" src="https://user-images.githubusercontent.com/17963713/47404892-87636500-d725-11e8-95e4-1e00e0b172bc.PNG">

### Acumulative flow
Bem parecido com o burnup esse gráfico apresenta a evolução do projeto em relação ao tempo das atividades em cada fase do processo. E auxilia a prever gargalos e direções do andamento do projeto.
<img width="339" alt="capture4" src="https://user-images.githubusercontent.com/17963713/47404907-92b69080-d725-11e8-9a10-171df98f3411.PNG">



OBS: Em todas essas métricas deve ser coletado pensando também nas labels, onde cada uma delas pode  ajudar a visualizar mais informações.

**Comment by alvesisaque** [comment]
Eu preciso de ao menos um revisor para fechar essa issue. amei e quero propor uma atividade em relação a isso na próxima sprint

**Comment by CalebeRios** [comment]
@alvesisaque Acho totalmente válido quebrar essa tarefa. Quais os documentos vamos realizar dentro do doc de arquitetura?

**Comment by alvesisaque** [comment]
@CalebeRios Ahh, eu não lembro de todos de cabeça agora. Mas acho que o resto da galera sabe. Se não responderem até a daily eu levo a proposta

**Comment by BrunoOliveiraDantas** [comment]
Dos artefatos do doc de arquitetura, poderíamos fazer o diagrama de casos de uso, de classe e pacotes. O que vocês acham?

**Comment by alvesisaque** [comment]
podemos usar como base esse aqui: https://dulce-work-schedule.github.io/especificacao/arquitetura.html mas não está tão bom

**Comment by alvesisaque** [comment]
O que podemos ter:
Diagrama de relações
Visão de Implementação
Diagrama de classes
Diagrama de Pacotes
Pipeline

**Comment by AmandaMuniz** [comment]
@MarthaDs disponibilizou um template no nosso drive, que pode ser encontrado nesse link: https://docs.google.com/document/d/1UzuG95RNfzLe-eW4c_T2QJyWNDot3AHZE0vWnDKgGhM/edit?usp=sharing. Deem uma olhada para gente poder adaptar a nossa realidade

**Comment by CalebeRios** [comment]
Criei uma branch para essa issue ```63_doc_arquitetura```. Estou fazendo o diagrama de pacotes já

**Comment by alvesisaque** [comment]
@CalebeRios Assim que criar o .md sobe por favor pra eu colocar informações lá
