### ISSUE TITLE
Configurar deploy da api

### ISSUE THREAD

**Issue by alvesisaque** [DesenhoSoftware-2018-2/wiki#68]
Nessa ssue deverá ser feito:
- Configurar ambiente da api;
- Configurar deploy;
- Configurar relacionamento e comunicação com o frontend (docker-compose)

**Comment by CalebeRios** [comment]
Configurei o deploy no heroku. Ele se encontra no link: https://thawing-hamlet-93187.herokuapp.com/
Irei fazer um tutorial para configuração do ambiente da API, mas não sei se irei fazer um nem para a API nem para o Web

**Comment by CalebeRios** [comment]
@CalebeRios https://frozen-ravine-88832.herokuapp.com/
