### ISSUE TITLE
Eu como, usuário desejo acessar uma sidenav para que eu possa navegar pelo sistema

### ISSUE THREAD

**Issue by alvesisaque** [DesenhoSoftware-2018-2/wiki#72]
Nessa história deverá ser feito:
Frontend:
- Criar sidenav no canto esquerdo da tela;
- Exibir informações do usuário (exibir todas as opções, informações do usuário como, perfil, avaliação  entre outros disponíveis no protótipo)

Critério de aceitaçao:
- Estar refletido no protótipo.

**Comment by AmandaMuniz** [comment]
O protótipo pode ser encontrado no  seguinte link: https://desenhosoftware-2018-2.github.io/wiki/prototipar
