### ISSUE TITLE
Daily - 31/10/2018

### ISSUE THREAD

**Issue by alvesisaque** [DesenhoSoftware-2018-2/wiki#74]
Todos os dias às 20:30.

Os integrantes do time deve enviar sua mensagem aqui, respondendo as 3 perguntas básicas da daily

**Comment by alvesisaque** [comment]
@alvesisaque Hoje eu não consegui trabalhar no projeto, por motivos de trabalho de ML e apresentação no trabalho. Amanhã pretendo finalizar as atividades da arquitetura e definir com a @Amymuniz o nosso pareamento.

**Comment by MarthaDs** [comment]
Hoje eu fui falar com a prof milene sobre diagrama de classe. Ela mostrou bastante preocupaçao a respeito do nosso modelo e pediu melhorias. Eu ainda hoje vou mandar um relatorio com as mudanças que ela pediu. Nao tive nenhuma dificuldade.

**Comment by AmandaMuniz** [comment]
@MarthaDs Hoje eu não fiz nada relacionado ao projeto. Mas espero subir os textos do doc de arquitetura e a primeira versão do diagrama de classe, porque mesmo estando errado é importante ter para manter o rastro. Amanhã vou começar a issue com o Isaque

**Comment by vitorcx** [comment]
Hoje fiz uma versão inicial do que será a monitoria no back-end, com a model, requisições de criação e acesso, mas acho que preciso da model do usuário pra completar. Amanhã pretendo parear pra finalizar o que for possível no back-end e começar o front da história de criar monitorias.

**Comment by BrunoOliveiraDantas** [comment]
Então hoje eu terminei o débito técnico que eu tinha que era o do forms, fiz uns textos  sobre elicitação e pré-rastreabilidade para terminar os pull request do hacktoberfest rsrs. Amanhã irei parear com o Calebe para começarmos a nossa issue

**Comment by joaovitor3** [comment]
@alvesisaque Aceitei o pr da branch de questionários e marquei o pareamento para amanhã

**Comment by lucianaribeiro** [comment]
Hoje eu iniciei o pareamento com a @inddiara mas ainda não commitamos e pretendo subir os léxicos. Sem problemas até o momento.

**Comment by CalebeRios** [comment]
@alvesisaque Eu não fiz nada relacionado ao projeto mas já tenho o diagrama de pacotes pronto. Então falta eu subir ele para a Wiki e ajudar no doc de arquitetura como um todo. Amanhã vou parear com o Bruno e a Martha para fazer o deploy tanto do React quanto do Django
