### ISSUE TITLE
Daily - 01/11/2018

### ISSUE THREAD

**Issue by lucianaribeiro** [DesenhoSoftware-2018-2/wiki#77]
Hoje às 20:30.

Os integrantes do time devem enviar sua mensagem aqui, respondendo as 3 perguntas básicas da daily.

**Comment by alvesisaque** [comment]
Boa noite, hoje eu finalizei o diagrama de relações da arquitetura. Nele é apresentado como é realizada a comunicação dentro do django, do react e por onde se comunicam. Amanhã pretendo trabalhar com a Amanda. Meu impedimento foi o trabalho de machine learning

**Comment by BrunoOliveiraDantas** [comment]
Boa noite, hoje eu e o Calebe tentamos iniciar o pareamento mas deu um problema de dependências na minha maquina e demoramos um tempinho para resolver, depois houve alguns imprevistos e não conseguimos terminar. Iremos parear o quanto antes para conseguirmos entregar até domingo.

**Comment by joaovitor3** [comment]
Boa noite, hoje eu e o Vitor pareamos de manhã e começamos fazer o form no repositório web para conversar com a API(que já está funcionando, mas ainda vamos mudar uns tipos de campos).
