### ISSUE TITLE
Adequar repositório à comunidade de software livre

### ISSUE THREAD

**Issue by joaovitor3** [DesenhoSoftware-2018-2/wiki#8]
Nessa issue deverá ser feito:

- [ ] Criação de labels para issues; 
- [x] Criação de template para abertura de Pull Requests; 
- [x] Criação de template para abertura de issues;
- [x] Seleção de licença para o repositório; 
- [x] Criação de README;
- [x] Criação de código de conduta;
- [x] Criação de guia de contribuição;
- [x] Realizar documentação das atividades realizas.

**Comment by alvesisaque** [comment]
https://img.shields.io/aur/license/yaourt.svg

**Comment by alvesisaque** [comment]
http://www.nacaolivre.com.br/open-source/licenca-gpl/
