### ISSUE TITLE
Daily - 06/11/2018

### ISSUE THREAD

**Issue by lucianaribeiro** [DesenhoSoftware-2018-2/wiki#83]
Hoje às 20:30.

Os integrantes do time devem enviar sua mensagem aqui, respondendo as 3 perguntas básicas da daily.

**Comment by alvesisaque** [comment]
@lucianaribeiro Boa noite time, hoje eu não consegui fazer AINDA. Mas agora a noite vou conversar com a @Amymuniz pra alinhar com o andamento da nossa história e evoluir o quanto conseguir o doc de arquitetura.

**Comment by AmandaMuniz** [comment]
@alvesisaque Hoje eu passei o dia mexendo na api, consegui consertar o erro de cors que estava dando, mas ainda estou mexendo nela. O problema agora e que ela salva o usuario, mas mesmo assim retorna um erro 400, mas quando da um get em usuario ela exibe. O esperado e terminar isso hoje e ai a historia vai estar finalizada.

**Comment by joaovitor3** [comment]
@alvesisaque Hoje não mexi na api por falta de tempo,mas ainda vou mexer hoje a noite
Tenho que consertar a parte do relacionamento da api ainda

**Comment by vitorcx** [comment]
Boa noite, hoje comecei a fazer uns testes pra verificar se o upload de imagem está funcionado, mas ainda não terminei.

**Comment by MarthaDs** [comment]
Hoje eu não fiz nada. Então não tive nenhuma dificuldade.

**Comment by lucianaribeiro** [comment]
Boa noite time. Hoje dei inicio à história com a @inddiara. Criamos a página de perfil e montamos uma navbar inicial. Tive uma pequena dificuldade pq o Dropdown do materialize não é mto legal pois ele sobrepõe o botão de dropdown, gostaria de saber se alguém sabe uma alternativa pra isso. Obrigada.
Segue o link para entender melhor https://materializecss.com/dropdown.html
