### ISSUE TITLE
Daily 08/11/2018

### ISSUE THREAD

**Issue by AmandaMuniz** [DesenhoSoftware-2018-2/wiki#86]
Hoje às 21:30.

Os integrantes do time devem enviar sua mensagem aqui, respondendo as 3 perguntas básicas da daily.

**Comment by alvesisaque** [comment]
@AmandaMuniz Boa noite, hoje eu trabalhei com a martha, bruno e amanda no diagrama de classe, também comecei a modelagem da nossa metodologia, quero validar com a professora milene e documentar na wiki. Tive impedimentos do meu projeto externo pq está chegando o fim da sprint e não consegui finalizar as minhas issues, então preciso correr com elas. Amanhã pretendo trabalhar pela manhã com os integrantes que se interessarem e tentar evoluir o diagrama de classe.

**Comment by AmandaMuniz** [comment]
@alvesisaque Hoje eu dei uma pequena revisada no diagrama de classes com o Isaque, o Bruno e a Martha. Encontramos alguns padrões que podem ser aplicados. Não mexi na minha issue da api de usuário, porque tirei o dia para estudar para as outras matérias. Amanhã, irei participar da evolução do Diagrama de classe e trabalhar na api
